document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh\'>");
document.writeln("<head>");
document.writeln("    <title>Orgent 官方网站</title>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\'>");
document.writeln("    <link rel=\'stylesheet\' href=\'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\'>");
document.writeln("    <link href=\'https://fonts.googleapis.com/css?family=Raleway:400,500,500i,700,800i\' rel=\'stylesheet\'>");
document.writeln("    <script src=\'js/jquery.min.js\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <nav class=\'navbar navbar-expand-sm   navbar-light bg-light\'>");
document.writeln("        <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarTogglerDemo03\' aria-controls=\'navbarTogglerDemo03\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("            <span class=\'navbar-toggler-icon\'></span>");
document.writeln("        </button>");
document.writeln("");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'navbarTogglerDemo03\'>");
document.writeln("            <ul class=\'navbar-nav mr-auto mt-2 mt-lg-0\'>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'index.html\'>Orgent 官方网站 <span class=\'sr-only\'>(current)</span></a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'download.html\'> &nbsp; 软件产品</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'tools.html\'> &nbsp; 工具</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'https://orgent.pythonanywhere.com\'> &nbsp; Orgent Blog</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'about.html\'> &nbsp; 关于我们</a>");
document.writeln("                </li>");
document.writeln("                <li class=\'nav-item\'>");
document.writeln("                    <a class=\'nav-link\' href=\'mailto:Contact@Orgent.top\'> &nbsp; 联系我们</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("</body>");
document.writeln("</html>");